if(LIBFWUPD_INCLUDE_DIRS AND LIBFWUPD_LIBRARIES)
    set(LIBFWUPD_FOUND TRUE)

else (LIBFWUPD_INCLUDE_DIRS AND LIBFWUPD_LIBRARIES)

  find_library (LIBFWUPD_LIBRARIES
    NAMES  fwupd libfwupd
  )
  
  find_path (LIBFWUPD_INCLUDE_DIRS
    NAMES fwupd.h
    PATH_SUFFIXES fwupd-1
    HINTS fwupd-1/libfwupd
  )

endif (LIBFWUPD_INCLUDE_DIRS AND LIBFWUPD_LIBRARIES)


#set(FWUPD_CFLAGS_OTHERS "")
#INTERFACE_COMPILE_OPTIONS ${FWUPD_CFLAGS_OTHERS}
if (LIBFWUPD_FOUND)
   add_library(LIBFWUPD SHARED IMPORTED)
   set_target_properties(LIBFWUPD PROPERTIES
       INTERFACE_INCLUDE_DIRECTORIES ${LIBFWUPD_INCLUDE_DIRS}
       IMPORTED_LOCATION ${LIBFWUPD_LIBRARIES}
       ) 
endif()
